services:
- type: web
  plan: starter
  name: minio-server
  healthCheckPath: /minio/health/live
  runtime: image
  image:
    url: docker.io/minio/minio:latest
  dockerCommand: minio server /data --address $HOST:$PORT --console-address $HOST:$CONSOLE_PORT
  autoDeploy: false
  disk:
    name: data
    sizeGB: 5
    mountPath: /data
  envVars:
  - key: MINIO_ROOT_USER
    generateValue: true
  - key: MINIO_ROOT_PASSWORD
    generateValue: true
  # - key: MINIO_BROWSER
  #   value: "off"
  - key: HOST
    value: "0.0.0.0"
  - key: PORT
    value: 9000
  - key: CONSOLE_PORT
    value: 9090

- type: web
  plan: starter
  name: minio-console
  runtime: docker
  repo: http://github.com/lexpierce/minio
  dockerContext: /
  dockerfilePath: ./Dockerfile
  envVars:
  - key: HOST
    value: "0.0.0.0"
  - key: PORT
    value: 10000
  - key: MINIO_HOST
    fromService:
      name: minio-server
      type: web
      property: host
  - key: MINIO_CONSOLE_PORT
    fromService:
      name: minio-server
      type: web
      property: CONSOLE_PORT
    
# - type: web
#   plan: starter
#   name: minio-console
#   runtime: docker
#   repo: https://github.com/minio/console.git
#   dockerfilePath: ./Dockerfile
#   dockerContext: /
#   dockerCommand: /bin/bash -c CONSOLE_MINIO_SERVER=https://$MINIO_HOST:$MINIO_PORT ./console server --port $CONSOLE_PORT
#   autoDeploy: false
#   envVars:
#   - key: CONSOLE_PBKDF_PASSPHRASE
#     generateValue: true
#   - key: CONSOLE_PBKDF_SALT
#     generateValue: true
#   - key: NODE_VERSION
#     value: 20.12.1
#   - key: MINIO_HOST
#     fromService:
#       name: minio-server
#       type: web
#       property: host
#   - key: MINIO_PORT
#     fromService:
#       name: minio-server
#       type: web
#       property: port
