services:
- type: web
  plan: standard
  name: minio-server
  healthCheckPath: /minio/health/live
  runtime: image
  image:
    url: docker.io/minio/minio:latest
  dockerCommand: minio server /data --address $HOST:$PORT --console-address $HOST:$CONSOLE_PORT
  autoDeploy: false
  disk:
    name: data
    sizeGB: 5
    mountPath: /data
  envVars:
  - key: MINIO_ROOT_USER
    generateValue: true
  - key: MINIO_ROOT_PASSWORD
    generateValue: true
  - key: HOST
    value: "0.0.0.0"
  - key: PORT
    value: 9000
  - key: CONSOLE_PORT
    value: 9090

# - type: web
#   name: minio-console
#   runtime: docker
#   repo: https://github.com/minio/console.git
#   dockerfilePath: ./Dockerfile
#   dockerContext: /
#   autoDeploy: false
#   envVars:
#   - key: CONSOLE_PBKDF_PASSPHRASE
#     generateValue: true
#   - key: CONSOLE_PBKDF_SALT
#     generateValue: true
#   - key: NODE_VERSION
#     value: 20.12.1
#   - key: CONSOLE_PORT
#     value: 9090
#   - key: CONSOLE_MINIO_SERVER
#     fromService:
#       name: minio-server
#       type: web
#       property: host
