services:
- type: web
  plan: pro
  name: minio-server
  healthCheckPath: /minio/health/live
  runtime: image
  image:
    url: docker.io/minio/minio:latest
  # dockerCommand: minio server /data --console-address ":$CONSOLE_PORT"
  dockerCommand: minio server /data
  autoDeploy: false
  disk:
    name: data
    sizeGB: 5
    mountPath: /data
  envVars:
  - key: MINIO_ROOT_USER
    generateValue: true
  - key: MINIO_ROOT_PASSWORD
    generateValue: true
  - key: MINIO_BROWSER
    value: "off"
  - key: PORT
    value: 9000
  # - key: CONSOLE_PORT
  #   value: 9090

# - type: web
#   name: minio-console
#   runtime: image
#   image:
#     url: minio/console:v0.30.0
#   dockerCommand: /bin/bash -c CONSOLE_MINIO_SERVER=https://$MINIO_HOST.onrender.com ./console server --port $PORT
#   autoDeploy: false
#   envVars:
#   - key: CONSOLE_PBKDF_PASSPHRASE
#     generateValue: true
#   - key: CONSOLE_PBKDF_SALT
#     generateValue: true
#   - key: PORT
#     value: 9090
#   - key: MINIO_HOST
#     fromService:
#       name: minio-server
#       type: web
#       property: host
